services:
  envoy:
    image: envoyproxy/envoy:v1.31-latest
    hostname: envoy
    volumes:
      - ./envoy.yaml:/etc/envoy/envoy.yaml
      - ./target/wasm32-wasi/release:/etc/envoy/proxy-wasm-plugins
    networks:
      - envoymesh
    ports:
      - "10000:10000"
networks:
  envoymesh: { }